### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 404forever1** [blank038/NyEconomy#3]
[01:21:42 INFO]: [NyEconomy] Enabling NyEconomy v1.7.0-SNAPSHOT
[01:21:42 ERROR]: Error occurred while enabling NyEconomy v1.7.0-SNAPSHOT (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'void com.zaxxer.hikari.HikariDataSource.<init>(com.zaxxer.hikari
.HikariConfig)' the class loader 'NyEconomy-1.7.0-SNAPSHOT.jar' @54277f70 of the current class, com/mc9y/nyeconomy/interfaces/impl/HikariDat
aSourceHandler, and the class loader 'QuickShop-Hikari-5.2.0.14.jar' @76219c01 for the method's defining class, com/zaxxer/hikari/HikariData
Source, have different Class objects for the type com/zaxxer/hikari/HikariConfig used in the signature (com.mc9y.nyeconomy.interfaces.impl.H
ikariDataSourceHandler is in unnamed module of loader 'NyEconomy-1.7.0-SNAPSHOT.jar' @54277f70, parent loader java.net.URLClassLoader @7de26
db8; com.zaxxer.hikari.HikariDataSource is in unnamed module of loader 'QuickShop-Hikari-5.2.0.14.jar' @76219c01, parent loader java.net.URL
ClassLoader @7de26db8)
        at NyEconomy-1.7.0-SNAPSHOT.jar/com.mc9y.nyeconomy.interfaces.impl.HikariDataSourceHandler.<init>(HikariDataSourceHandler.java:29) ~
[NyEconomy-1.7.0-SNAPSHOT.jar:?]
        at NyEconomy-1.7.0-SNAPSHOT.jar/com.mc9y.nyeconomy.handler.MySqlStorgeHandler.<init>(MySqlStorgeHandler.java:41) ~[NyEconomy-1.7.0-S
NAPSHOT.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
        at NyEconomy-1.7.0-SNAPSHOT.jar/com.mc9y.nyeconomy.handler.AbstractStorgeHandler.setHandler(AbstractStorgeHandler.java:73) ~[NyEcono
my-1.7.0-SNAPSHOT.jar:?]
        at NyEconomy-1.7.0-SNAPSHOT.jar/com.mc9y.nyeconomy.Main.onEnable(Main.java:57) ~[NyEconomy-1.7.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[leaf-1.20.4.jar:gi
t-Leaf-"3669cb6"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaf-1.20.4.jar:git-Leaf-"
3669cb6"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:661) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:572) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:657) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:417) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:21:42 INFO]: [NyEconomy] Disabling NyEconomy v1.7.0-SNAPSHOT

**Comment by blank038** [comment]
可以通过在 AyCore 的 config.yml 中关闭 hikari 设定来使用原生连接而不走连接池。

**Comment by 404forever1** [comment]
没有用，插件无法加载

**Comment by blank038** [comment]
> 没有用，插件无法加载

经过测试复现不出来这个错误，我尝试使用与你一致的版本进行测试。

**Comment by blank038** [comment]
> 没有用，插件无法加载

经过测试相同核心版本、相同插件版本的情况下复现不出来，目前我取消了 HikariCP 依赖的加载，你可以再次尝试看看是否有问题。

**Comment by 404forever1** [comment]
很容易复现的，只需要安装nye ，aycore ，quickshop最新版本，nye打开mysql，就复现了，我下载了一个很老的quickshop，错误就消失了。先顶着把
